name: winkler-env
channels:
- qttesting
- conda-forge
- defaults
dependencies:
- python=3.6
- gsw=3.2.0=py36_0
- matplotlib=2.1.1=py36_0
- pyserial=3.4=py36_0
- xlrd=1.1.0=py36_0
- pip:
  - pyqt5==5.9.2
